# Generated by Django 3.1.5 on 2021-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapi', '0003_bookingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='advisor_id',
            field=models.IntegerField(blank=True),
        ),
    ]
