# Generated by Django 3.1.5 on 2021-05-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adapi', '0006_auto_20210505_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookingdetail',
        ),
    ]
